#!/usr/bin/env python3
"""
Export YouTube cookies from Chrome/Edge browser for use in GitHub Actions.

Run this on your local PC when logged into YouTube in Chrome.
Then copy the output to GitHub secret: YOUTUBE_COOKIES

Usage:
    python export_yt_cookies.py [chrome|edge]
    python export_yt_cookies.py > cookies.txt
"""
import sys, os, sqlite3, shutil, tempfile, base64, json

# Try to import browser_cookie3 first (cleanest method)
try:
    import browser_cookie3 as bc3

    def export_via_browser_cookie3(browser='chrome'):
        print("Using browser_cookie3...", file=sys.stderr)
        if browser == 'edge':
            cookies = bc3.edge(domain_name='.youtube.com')
        else:
            cookies = bc3.chrome(domain_name='.youtube.com')

        lines = [
            "# Netscape HTTP Cookie File",
            "# https://curl.haxx.se/docs/http-cookies.html",
            "# This file was generated by export_yt_cookies.py",
            ""
        ]
        count = 0
        for cookie in cookies:
            if 'youtube' not in cookie.domain and 'google' not in cookie.domain:
                continue
            secure = "TRUE" if cookie.secure else "FALSE"
            expiry = int(cookie.expires) if cookie.expires else 0
            http_only = "TRUE" if cookie.has_nonstandard_attr('HttpOnly') else "FALSE"
            lines.append(
                f"{cookie.domain}\t{http_only}\t{cookie.path}\t{secure}\t{expiry}\t{cookie.name}\t{cookie.value}"
            )
            count += 1

        print(f"Exported {count} cookies", file=sys.stderr)
        return "\n".join(lines)

    BROWSER = sys.argv[1] if len(sys.argv) > 1 else 'chrome'
    output = export_via_browser_cookie3(BROWSER)
    print(output)
    sys.exit(0)

except ImportError:
    print("browser_cookie3 not installed. Trying manual extraction...", file=sys.stderr)

# Manual extraction from Chrome SQLite database
def get_chrome_cookies():
    import platform
    system = platform.system()

    if system == "Windows":
        paths = [
            os.path.expandvars(r"%LOCALAPPDATA%\Google\Chrome\User Data\Default\Network\Cookies"),
            os.path.expandvars(r"%LOCALAPPDATA%\Google\Chrome\User Data\Default\Cookies"),
            os.path.expandvars(r"%LOCALAPPDATA%\Microsoft\Edge\User Data\Default\Network\Cookies"),
        ]
    elif system == "Darwin":
        home = os.path.expanduser("~")
        paths = [
            f"{home}/Library/Application Support/Google/Chrome/Default/Cookies",
        ]
    else:
        home = os.path.expanduser("~")
        paths = [
            f"{home}/.config/google-chrome/Default/Cookies",
        ]

    db_path = None
    for p in paths:
        if os.path.exists(p):
            db_path = p
            print(f"Found cookies at: {p}", file=sys.stderr)
            break

    if not db_path:
        print("Could not find Chrome cookies database!", file=sys.stderr)
        print("Please install browser_cookie3: pip install browser-cookie3", file=sys.stderr)
        sys.exit(1)

    # Copy to temp (Chrome locks the file)
    tmp = tempfile.mktemp(suffix='.db')
    shutil.copy2(db_path, tmp)

    conn = sqlite3.connect(tmp)
    cursor = conn.execute(
        "SELECT host_key, path, is_secure, expires_utc, name, value, encrypted_value "
        "FROM cookies WHERE host_key LIKE '%youtube%' OR host_key LIKE '%google%'"
    )

    lines = [
        "# Netscape HTTP Cookie File",
        "# Exported from Chrome",
        ""
    ]

    count = 0
    for host, path, secure, expires, name, value, enc_value in cursor.fetchall():
        if not value and enc_value:
            # On Windows, cookies are encrypted. Skip encrypted ones without decryption.
            continue
        secure_str = "TRUE" if secure else "FALSE"
        # Chrome stores expiry in microseconds since 1601
        expiry = max(0, (expires - 11644473600000000) // 1000000) if expires else 0
        lines.append(f"{host}\tTRUE\t{path}\t{secure_str}\t{expiry}\t{name}\t{value}")
        count += 1

    conn.close()
    os.unlink(tmp)

    print(f"Exported {count} cookies (note: encrypted cookies skipped)", file=sys.stderr)
    if count == 0:
        print("WARNING: 0 cookies exported. Chrome may be encrypting them.", file=sys.stderr)
        print("Install browser-cookie3 for proper decryption: pip install browser-cookie3", file=sys.stderr)

    return "\n".join(lines)


output = get_chrome_cookies()
print(output)
